---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Clustring/Clustring.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/200882/master/file/figures/Clustring/Clustring.png"
    folder_url: "/users/74776/articles/200882/master/folder/figures/Clustring"
